package com.boardly.constants

const val USERS_NODE = "users"
const val EVENTS_NODE = "events"
const val NOTIFY_SETTINGS_NODE = "notifySettings"
const val PLAYERS_NODE = "players"
const val PENDING_EVENTS_NODE = "pending"
const val ACCEPTED_EVENTS_NODE = "accepted"
const val CREATED_EVENTS_NODE = "created"
const val INTERESTING_EVENTS_NODE = "interesting"
const val CHATS_NODE = "chats"
const val EVENTS_WITH_INTEREST = "eventsWithInterest"
const val PLACES_NODE = "places"
const val COLLECTIONS_NODE = "collections"

const val NAME_CHILD = "name"
const val PROFILE_PICTURE_CHILD = "profilePicture"
const val RATING_HASHES = "ratingHashes"
const val TIMESTAMP_CHILD = "timestamp"
const val NOTIFICATION_TOKEN_CHILD = "notificationToken"